### ISSUE TITLE
How can I change this code to have the list of projects name as well in its drop-down like the reporters drop-down?

### ISSUE THREAD

**Issue by parisnk** [parisnk/projectDailyReport#8]
https://github.com/parisnk/projectDailyReport/blob/b219e61652c36fc2c4295531e87c06153acfc4b0/routes/index.js#L11

**Comment by jristow** [comment]
It appears like you are trying to pass in an array of callback functions to your route definition. I think if you put the .allMembersReports and .allProjects items inside of brackets, it may fix your problem.
See example from Express documentation:
```js
var cb0 = function (req, res, next) {
  console.log('CB0')
  next()
}

var cb1 = function (req, res, next) {
  console.log('CB1')
  next()
}

var cb2 = function (req, res) {
  res.send('Hello from C!')
}

app.get('/example/c', [cb0, cb1, cb2])
```

**Comment by jristow** [comment]
Another option, since you are using express.Router to define the route, may be the following (from express documentation as well).

> express.Router
Use the express.Router class to create modular, mountable route handlers. A Router instance is a 
complete middleware and routing system; for this reason, it is often referred to as a “mini-app”.
    
>The following example creates a router as a module, loads a middleware function in it, defines some 
routes, and mounts the router module on a path in the main app.
    
>Create a router file named birds.js in the app directory, with the following content:
```js
    var express = require('express')
    var router = express.Router()

    // middleware that is specific to this router
    router.use(function timeLog (req, res, next) {
      console.log('Time: ', Date.now())
      next()
    })
    // define the home page route
    router.get('/', function (req, res) {
      res.send('Birds home page')
    })
    // define the about route
    router.get('/about', function (req, res) {
      res.send('About birds')
    })
    
    module.exports = router
```
>Then, load the router module in the app:
```js
    var birds = require('./birds')
    
    // ...
    
    app.use('/birds', birds)
```
>The app will now be able to handle requests to /birds and /birds/about, as well as call the timeLog 
middleware function that is specific to the route. 

src: [https://expressjs.com/en/guide/routing.html](url)
